# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29a97c65b479acf11a387046edf9adbb2f45ee72a6c2f40719f9fca5496e830a0e11376a89314ff6a71ac7a99fc33de7a27c81423e8b86ab3e5dfd4e681d41f

test:
  secret_key_base: 89e4ef8b10966dc764ff5a804e401b1d6a342c1b802c3d7a32f60bdc34d982c00e9b125a210eb7267a868498ff08b6efa7f346e0b340df018b66f3869fac7b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
